@urlPrefix = https://blue-shape-3166.us-east1.akkaserverless.app
@orderId = cart-1
@skuId = sku-3
@skuName = sku name 3
@quantity = 1
@orderItemId = 32baaaff-0282-4c06-817f-2df6c0cb8167

### io.mystore.shipping.action.StockItemFrontend.createStockItems

curl -XPOST -H "Content-Type: application/json" -d '{
  "sku_name":"{{skuName}}",
  "quantity":{{quantity}}}'
  {{urlPrefix}}/stock-item-frontend/{{skuId}}/create

### io.mystore.shipping.api.ShipOrderItemService.GetShipOrderItem

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/ship-order-items/{{orderItemId}}'

### io.mystore.shipping.api.ShipOrderService.GetShipOrder

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/ship-order/{{orderId}}'
