
@urlPrefix = https://spring-frog-8357.us-east1.kalix.app
@stockOrderId = stock-order-1
@skuId = sku-4
@skuName = sku name 4
@quantity = 4

### io.mystore.stock.api.StockOrderService.CreateStockOrder

curl -XPOST -H "Content-Type: application/json" -d '{
  "sku_id":"{{skuId}}",
  "sku_name":"{{skuName}}",
  "quantity":{{quantity}}}'
  {{urlPrefix}}/stork-orders/{{stockOrderId}}/create-stock-order

### io.mystore.stock.api.StockOrderService.GetStockOrder

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/stock-orders/{{stockOrderId}}'
