
# @urlPrefix = http://localhost:9000
@urlPrefix = https://blue-shape-3166.us-east1.akkaserverless.app
@customerId = customer-1
@orderId = cart-1
@productId = product-1
@productName = product name 1
@quantity = 1
# @checkedOutUtc = 2022-01-01T00:00:00.000-0500
@checkedOutUtc =
# @shippedUtc = 2022-01-01T00:00:00.000-0500
@shippedUtc =
# @deliveredUtc = 2022-01-01T00:00:00.000-0500
@deliveredUtc =
# @deletedUtc = 2022-01-12T00:00:00.000-0500
@deletedUtc =

### io.mystore.order.api.OrderService.ShippedCart

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/shipped

### io.mystore.order.api.OrderService.DeliveredCart

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/delivered

### io.mystore.order.api.OrderService.DeleteCart

curl -XDELETE -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/delete

### io.mystore.order.api.OrderService.GetOrder

curl -XGET -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}
