
@urlPrefix = https://blue-shape-3166.us-east1.akkaserverless.app
@skuId = sku-2
@orderId = cart-1

### io.mystore.shipping.view.BackOrderedShipOrderItems.GetBackOrderedShipOrderItems

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/back-ordered-ship-order-items'

### io.mystore.shipping.view.BackOrderedShipOrderItemsBySku.GetBackOrderedShipOrderItemsBySku

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/back-ordered-ship-order-items-by-sku?skuId={{skuId}}'

### io.mystore.shipping.view.AvailableStockItems.GetAvailableStockItems

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/available-stock-items'

### io.mystore.shipping.view.AvailableShipSkuItems.GetAvailableShipSkuItems

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/available-ship-sku-items?sku_id={{skuId}}'

### io.mystore.shipping.view.ShippedStockItems.GetShippedStockItems

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/shipped-stock-items'
