
@urlPrefix = https://wispy-sun-4785.us-east1.akkaserverless.app
@customerId = customer-1
@orderId = cart-1
@skuId = sku-1
@skuName = sku name 1
@quantity = 1
# @checkedOutUtc = 2022-01-01T00:00:00.000-0500
@checkedOutUtc =
# @shippedUtc = 2022-01-01T00:00:00.000-0500
@shippedUtc =
# @deliveredUtc = 2022-01-01T00:00:00.000-0500
@deliveredUtc =
# @canceledUtc = 2022-01-12T00:00:00.000-0500
@canceledUtc =
# @returnedUtc = 2022-01-12T00:00:00.000-0500
@returnedUtc =

### io.mystore.order.api.OrderService.ShippedOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/shipped

### io.mystore.order.api.OrderService.DeliveredOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/delivered

### io.mystore.order.api.OrderService.ReturnedOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/returned

### io.mystore.order.api.OrderService.CanceledOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/canceled

### io.mystore.order.api.OrderService.ReturnededOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/returned

### io.mystore.order.api.OrderService.GetOrder

curl -XGET -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}
