
@urlPrefix = https://floral-band-7795.us-east1.akkaserverless.app
@customerId = customer-1
@fromDate = 2022-01-01T00:00:00.000-05:00
@toDate = 2023-01-01T00:00:00.000-05:00

### io.mystore.cart.view.CartsByCustomer.GetCartsByCustomer

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/carts-by-customer?customer_id={{customerId}}'

### io.mystore.cart.view.CartsByCustomerByDate.GetCartsByCustomerByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/carts-by-customer-by-date?customer_id={{customerId}}&from_date={{fromDate}}&to_date={{toDate}}'

### io.mystore.cart.view.CartsByDate.GetCartsByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/carts-by-date?from_date={{fromDate}}&to_date={{toDate}}'
