
@urlPrefix = https://empty-moon-4960.us-east1.kalix.app
@orderId = cart-1

### io.mystore.order.api.OrderService.ShippedOrder

PUT {{urlPrefix}}/order/{{orderId}}/shipped
Content-Type: application/json

### io.mystore.order.api.OrderService.DeliveredOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/delivered

### io.mystore.order.api.OrderService.ReturnedOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/returned

### io.mystore.order.api.OrderService.CanceledOrder

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/order/{{orderId}}/canceled

### io.mystore.order.api.OrderService.GetOrder

GET {{urlPrefix}}/order/{{orderId}}
Content-Type: application/json
