@urlPrefix = https://floral-band-7795.us-east1.akkaserverless.app
@orderId = cart-1
@skuId = sku-1
@skuName = sku name 1
@quantity = 1
@orderItemId = a6f75256-83db-481f-ba3f-f32d40f251f0

### io.mystore.shipping.action.StockItemFrontend.createStockItems

curl -XPOST -H "Content-Type: application/json" -d '{
  "sku_name":"{{skuName}}",
  "quantity":{{quantity}}}'
  {{urlPrefix}}/stock-item-frontend/{{skuId}}/create

### io.mystore.order.api.OrderService.GetOrder

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/order/{{orderId}}'

### io.mystore.shipping.api.ShipOrderService.GetShipOrder

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/ship-order/{{orderId}}'

### io.mystore.shipping.api.ShipOrderItemService.GetShipOrderItem

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/ship-order-items/{{orderItemId}}'
