
# @urlPrefix = http://localhost:9000
@urlPrefix = https://bold-resonance-3890.us-east1.akkaserverless.app
@customerId = customer-1
@orderId = cart-1
@productId = product-2
@productName = product name 2
@quantity = 1
# @checkedOutUtc = 2022-01-01T00:00:00.000-0500
@checkedOutUtc =
# @shippedUtc = 2022-01-01T00:00:00.000-0500
@shippedUtc =
# @deliveredUtc = 2022-01-01T00:00:00.000-0500
@deliveredUtc =
# @deletedUtc = 2022-01-12T00:00:00.000-0500
@deletedUtc =
@fromDate = 2022-01-01T00:00:00.000-05:00
@toDate = 2023-01-01T00:00:00.000-05:00

### io.order.api.OrderService.GetOrder

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/order/{{orderId}}'

### io.order.view.OrdersByCustomerByDate.GetOrdersByCustomerByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/orders-by-customer-by-date?customer_id={{customerId}}&from_date={{fromDate}}}}&to_date={{toDate}'

### workaround POST until GET is fixed

curl -XPOST -H "Content-Type: application/json" -d '{
  "customerId": "{{customerId}}",
  "fromDate": "{{fromDate}}",
  "toDate": "{{toDate}}"
  }' '{{urlPrefix}}/orders-by-customer-by-date'

### io.order.view.OrdersByDate.GetOrdersByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/orders-by-date?from_date={{fromDate}}&to_date={{toDate}}'

### workaround POST until GET is fixed

curl -XPOST -H "Content-Type: application/json" -d '{
  "fromDate": "{{fromDate}}",
  "toDate": "{{toDate}}"
  }' '{{urlPrefix}}/orders-by-date'
