
# @urlPrefix = http://localhost:9000
@urlPrefix = https://bold-resonance-3890.us-east1.akkaserverless.app
@customerId = customer-1
@cartId = cart-1
@productId = product-1
@productName = product name 1
@quantity = 1
# @checkedOutUtc = 2022-01-01T00:00:00.000-0500
@checkedOutUtc =
# @shippedUtc = 2022-01-01T00:00:00.000-0500
@shippedUtc =
# @deliveredUtc = 2022-01-01T00:00:00.000-0500
@deliveredUtc =
# @deletedUtc = 2022-01-12T00:00:00.000-0500
@deletedUtc =
@fromDate = 2022-01-01T00:00:00.000-0500
@toDate = 2023-01-01T00:00:00.000-0500

### io.shopping.cart.ShoppingCartService.AddItem

curl -XPOST -H "Content-Type: application/json" -d '{
  "customer_id":"{{customerId}}",
  "product_id":"{{productId}}",
  "product_name":"{{productName}}",
  "quantity":{{quantity}}
  }' {{urlPrefix}}/cart/{{cartId}}/items/add

### io.shopping.cart.ShoppingCartService.ChangeItem

curl -XPUT -H "Content-Type: application/json" -d '{
  "quantity":{{quantity}}
  }' {{urlPrefix}}/cart/{{cartId}}/items/{{productId}}/change

### io.shopping.cart.ShoppingCartService.RemoveItem

curl -XDELETE -H "Content-Type: application/json"
  {{urlPrefix}}/cart/{{cartId}}/items/{{productId}}/remove

### io.shopping.cart.ShoppingCartService.CheckoutCart

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/cart/{{cartId}}/checkout

### io.shopping.cart.ShoppingCartService.ShippedCart

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/cart/{{cartId}}/shipped

### io.shopping.cart.ShoppingCartService.DeliveredCart

curl -XPUT -H "Content-Type: application/json"
  {{urlPrefix}}/cart/{{cartId}}/delivered

### io.shopping.cart.ShoppingCartService.DeleteCart

curl -XDELETE -H "Content-Type: application/json"
  {{urlPrefix}}/cart/{{cartId}}/delete

### io.shopping.cart.ShoppingCartService.SetDates

curl -XPUT -H "Content-Type: application/json" -d '{
  "checked_out_utc":"{{checkedOutUtc}}",
  "shipped_utc":"{{shippedUtc}}",
  "delivered_utc":"{{deliveredUtc}}",
  "deleted_utc":"{{deletedUtc}}"
  }' {{urlPrefix}}/cart/{{cartId}}/dates

### io.shopping.cart.ShoppingCartService.GetCart

curl -XGET -H "Content-Type: application/json"
  {{urlPrefix}}/cart/{{cartId}}

### io.shopping.cart.view.CustomerOrdersByDate.GetCustomerOrdersByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/customer-orders-by-date?customer_id={{customerId}}&from_date={{fromDate}}&to_date={{toDate}}'

### io.shopping.cart.view.CustomerShoppingCarts.GetShoppingCarts

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/shoppng-carts?customer_id={{customerId}}'

### io.shopping.cart.view.OrdersByDate.GetOrdersByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/orders-by-date?from_date={{fromDate}}&to_date={{toDate}}'

### io.shopping.cart.view.PurchasedProducts.GetPurchasedProductsByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/purchased-products-by-date?product_id={{productId}}&from_date={{fromDate}}&to_date={{toDate}}'

### io.shopping.cart.api.PurchasedProductService.GetPurchasedProduct

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/product/{{customerId}}/{{cartId}}/{{productId}}'
